apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: reservation-pod-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      'io.kompose.service': 'reservation'
  duration: "30s"
